config/routes.rb
Rails.application.routes.draw do
  resources :reviews do
    member do
      get 'show_image'
    end
    collection do
      get 'new_ajax'
      get 'list_by_qua'
      post 'create_ajax'
    end
  end

  resources :quas do
    member do
      get 'show_image'
    end
    collection do
      post 'create_ajax'
      get 'ajax_qua_list'
    end
  end

  root 'welcome#index'
  get 'hotels' => 'hotels#rakuten_web_search'

end

app/models/qua.rb
class Qua < ActiveRecord::Base
  scope :named, ->(q) { where 'name like ?', "%#{q}%" }
  def self.random
    order("random()").limit(1)
  end
  def self.center
    random = Qua.random
    center = random[0] unless random.nil? 
    if center.nil? || center["latitude"] == nil || center["longitude"] == nil
      q = Qua.new
      q.latitude = 38.743224
      q.longitude = 140.715955
      center = q
    end
    center
  end
end

app/controllers/quas_controller.rb
class QuasController < ApplicationController
  before_action :set_qua, only: [:show, :edit, :update, :destroy, :show, :show_image]

  # GET /quas
  # GET /quas.json
  def index
    @quas = Qua.all
  end
  
  def ajax_qua_list
    @quas = Qua.named(params[:q]).limit(10)
  end
  
  # GET /quas/1
  # GET /quas/1.json
  def show
  end

  # GET /quas/new
  def new
    @qua = Qua.new
  end

  # GET /quas/1/edit
  def edit
  end

  # GET /quas/1/edit
  def edit_ajax
    @qua = Qua.find(:id)

  end

  # POST /quas
  # POST /quas.json
  def create
    @qua = quaWithUploadedFile(qua_params)

    respond_to do |format|
      if @qua.save
        format.html { redirect_to @qua, notice: 'Qua was successfully created.' }
        format.json { render :show, status: :created, location: @qua }
      else
        format.html { render :new }
        format.json { render json: @qua.errors, status: :unprocessable_entity }
      end
    end
  end
  def create_ajax
    @qua = quaWithUploadedFile(qua_params)

    respond_to do |format|
      if @qua.save
        format.json {
          render json: { :qua => @qua }
        }
      else
        format.json { render json: @qua.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quas/1
  # PATCH/PUT /quas/1.json
  def update
    respond_to do |format|
      q = quaWithUploadedFile(qua_params).attributes
      q["id"] = params[:id]

      if @qua.update(q)
        format.html { redirect_to @qua, notice: 'Qua was successfully updated.' }
        format.json { render :show, status: :ok, location: @qua }
      else
        format.html { render :edit }
        format.json { render json: @qua.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quas/1
  # DELETE /quas/1.json
  def destroy
    @qua.destroy
    respond_to do |format|
      format.html { redirect_to quas_url, notice: 'Qua was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def show_image
    send_data @qua.image1, :type => 'image/jpeg', :disposition => 'inline'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qua
      @qua = Qua.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def qua_params
      params.require(:qua).permit(:name, :latitude, :longitude, 
        :quality, :effect, :url, :stay_required, :price, 
        :image1_caption, :image1, :image2_caption, :image2, :image3_caption, :image3)
    end

    def quaWithUploadedFile(qua_params)
      upload_file = qua_params[:image1]
      qua = {}
      qua[:name] = qua_params[:name]
      qua[:latitude] = qua_params[:latitude]
      qua[:longitude] = qua_params[:longitude]
      qua[:quality] = qua_params[:quality]
      qua[:effect] = qua_params[:effect]
      qua[:url] = qua_params[:url]
      qua[:stay_required] = qua_params[:stay_required]
      qua[:price] = qua_params[:price]
      qua[:image1_caption] = qua_params[:image1_caption]
      if upload_file != nil && upload_file != ''
         qua[:image1] = upload_file.read
      end
      Qua.new(qua)
    end
end

app/helpers/quas_helper.rb
module QuasHelper
end

app/views/quas/_form.html.erb
<%= form_for(@qua) do |f| %>
  <% if @qua.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@qua.errors.count, "error") %> prohibited this qua from being saved:</h2>

      <ul>
      <% @qua.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "名前" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :latitude, "緯度" %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude, "経度" %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :quality, "泉質" %><br>
    <%= f.text_field :quality %>
  </div>
  <div class="field">
    <%= f.label :effect, "効能" %><br>
    <%= f.text_field :effect %>
  </div>
  <div class="field">
    <%= f.label :url, "URL" %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :stay_required, "宿泊の要否" %><br>
    <%= f.radio_button :stay_required, "0" %>不要
    <%= f.radio_button :stay_required, "1" %>必要
  </div>
  <div class="field">
    <%= f.label :price, "値段" %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :image1_caption, "画像タイトル" %><br>
    <%= f.text_field :image1_caption %>
  </div>
  <div class="field">
    <%= f.label :image1, "画像" %><br>
    <%= f.file_field :image1, accept: "image/jpeg" %>
  </div>
  <div class="actions">
    <%= f.submit "登録する", :class => "btn btn-sm btn-default" %>
  </div>
<% end %>

app/views/quas/_form2.html.erb
<%= form_for(@qua, :url => {:action => 'create_ajax', :controller => 'quas'}, :remote => true) do |f| %>
  <% if @qua.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@qua.errors.count, "error") %> prohibited this qua from being saved:</h2>

      <ul>
      <% @qua.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <div class="field">
    <span id="label">名前:</span>
    <span><%= f.text_field :name %></span>
    <button type="button" class='btn btn-default btn-xs' onclick="getLatLngFromKeywordOnQuaEntry(qua_name.value, null)">検索</button>
  </div>
  <div class="field">
    <span>緯度:</span>
    <span><%= f.text_field :latitude %></span>
  </div>
  <div class="field">
    <span>経度:</span>
    <span><%= f.text_field :longitude %></span>
  </div>
  <div class="field">
    <span style="vertical-align: top;">泉質:</span>
    <span><%= f.text_area :quality, style: "width: 220px; height: 60px; resize: none;" %></span>
  </div>
  <div class="field">
    <span style="vertical-align: top;">効能:</span>
    <span><%= f.text_area :effect, style: "width: 220px; height: 60px; resize: none;" %></span>
  </div>
  <div class="field">
    <span>Webサイト:</span>
    <span><%= f.text_field :url %></span>
  </div>
  <div class="field">
    <span>宿泊の必要:</span>
    <span><%= f.radio_button :stay_required, "0" %>無
    <%= f.radio_button :stay_required, "1" %>有</span>
  </div>
  <div class="field">
    <span>料金:</span>
    <span><%= f.text_field :price %>円</span>
  </div>
  <div class="field">
    <span>画像タイトル</span>
    <span><%= f.text_field :image1_caption %></span>
  </div>
  <div class="field">
    <span>画像ファイル</span>
    <span><%= f.file_field :image1, accept: "image/jpeg" %></span>
  </div>
<% end %>

app/views/quas/_qua_list.html.erb
  <% quas.each do |q| %>
  <li>
    <div class="qua_search_result">
     <div style="overflow:hidden;">
      <div style="float:left;">
       <div class="qua_name"><b><%= q.name %></b></div>
       <div class="qua_info" style="display:none;">
         <%= q.id %>,<%= q.name %>,<%= q.latitude %>,<%= q.longitude %>,<%= q.quality %>,<%= q.effect %>,<%= q.stay_required %>,<%= q.price  %>,<%= q.url  %>,<%= q.image1_caption %>,<%= q.image1.nil? ? '<img class="img_info_window" src="/assets/onsen.png">' : '<img class="img_info_window" src="/quas/' + q.id.to_s + '/show_image">' %>
       </div>
       <div><button id="link_enter_review_<%= q.id %>" class="btn btn-sm btn-link review_dialog_open" onclick="reviewEntryLinkClicked(this)">レビューを書く</button></div>
       <div><button id="link_show_review_<%= q.id %>" class="btn btn-sm btn-link review_dialog_open" onclick="reviewLinkClicked(this)">レビューを見る</button></div>
      </div>
      <%= q.image1.present? ? image_tag(show_image_qua_path(q), style:'max-width:50px;max-haight:50px;margin-right:10px;', align:'right') : image_tag('onsen.png', style:'max-width:50px;max-haight:50px;margin-right:10px;', align:'right') %>
     </div>
    </div>
  </li>
  <% end %>

app/views/quas/ajax_qua_list.js.erb
$("#qua_list").html("<%= escape_javascript(render 'qua_list', quas: @quas) %>");

app/views/quas/edit.html.erb
<h1>Editing qua</h1>

<%= render 'form' %>

<%= link_to 'Show', @qua %> |
<%= link_to 'Back', quas_path %>

app/views/quas/index.html.erb
<h1>Listing quas</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>名称</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Quality</th>
      <th>Effect</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quas.each do |qua| %>
      <tr>
        <td><%= qua.id %></td>
        <td><%= qua.name %></td>
        <td><%= qua.latitude %></td>
        <td><%= qua.longitude %></td>
        <td><%= qua.quality %></td>
        <td><%= qua.effect %></td>
        <td><%= qua.url %></td>
        <td><%= link_to 'Show', qua %></td>
        <td><%= link_to 'Edit', edit_qua_path(qua) %></td>
        <td><%= link_to 'Destroy', qua, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Qua', new_qua_path %>

app/views/quas/new.html.erb
<h1>New qua</h1>

<%= render 'form' %>

<%= link_to 'Back', quas_path %>

app/views/quas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @qua.name %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @qua.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @qua.longitude %>
</p>

<p>
  <strong>Quality:</strong>
  <%= @qua.quality %>
</p>

<p>
  <strong>Effect:</strong>
  <%= @qua.effect %>
</p>

<p>
  <strong>Url:</strong>
  <%= @qua.url %>
</p>

<%= link_to 'Edit', edit_qua_path(@qua) %> |
<%= link_to 'Back', quas_path %>